# Site settings
title: Software Apprentice
name: Christopher Markus

description: Hi! I am a full-stack .Net developer. I also have experience in Middleware and DevOps. Not stopping there, I keep learning as I go.

baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://192.168.99.100:4000/" # the base hostname & protocol for your site
url: "http://www.softwareapprentice.com/"

#customize your colors: http://www.getmdl.io/customize/index.html
primary_color: grey
accent_color: orange

google_analytics:
email: getmarkus@msn.com
facebook:
github: getmarkus
linkedin: cmarkus
twitter: 
stackoverflow: 5314425/christopher-markus?tab=profile
rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
atom: 
youtube: # channel/<your_long_string> or user/<user-name>
googleplus: # anything in your profile username that comes after plus.google.com/
dribbble:
flickr:
instagram:
pinterest:

# Build settings
markdown: redcarpet

excerpt_separator: <!--more-->

exclude: _posts/images

#redcarpet:
#  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
