/** @type {import('tailwindcss').Config} */
// https://noumenal.es/notes/tailwind/custom-color-aliases/
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        "sand": {
          50: "#f8f8f8",
          100: "#f3f3f3",
          DEFAULT: "#f3f3f3",
          200: "#dcdcdc",
          300: "#bdbdbd",
          400: "#989898",
          500: "#7c7c7c",
          600: "#656565",
          700: "#525252",
          800: "#464646",
          900: "#3d3d3d",
          950: "#292929",
        },
      },
      typography: ({ theme }) => ({
        "sand": {
          css: {
            '--tw-prose-body': theme('colors.sand[800]'),
            '--tw-prose-headings': theme('colors.sand[900]'),
            '--tw-prose-lead': theme('colors.sand[700]'),
            '--tw-prose-links': theme('colors.sand[900]'),
            '--tw-prose-bold': theme('colors.sand[900]'),
            '--tw-prose-counters': theme('colors.sand[600]'),
            '--tw-prose-bullets': theme('colors.sand[400]'),
            '--tw-prose-hr': theme('colors.sand[300]'),
            '--tw-prose-quotes': theme('colors.sand[900]'),
            '--tw-prose-quote-borders': theme('colors.sand[300]'),
            '--tw-prose-captions': theme('colors.sand[700]'),
            '--tw-prose-code': theme('colors.sand[900]'),
            '--tw-prose-pre-code': theme('colors.sand[100]'),
            '--tw-prose-pre-bg': theme('colors.sand[900]'),
            '--tw-prose-th-borders': theme('colors.sand[300]'),
            '--tw-prose-td-borders': theme('colors.sand[200]'),
            '--tw-prose-invert-body': theme('colors.sand[200]'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-lead': theme('colors.sand[300]'),
            '--tw-prose-invert-links': theme('colors.white'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.sand[400]'),
            '--tw-prose-invert-bullets': theme('colors.sand[600]'),
            '--tw-prose-invert-hr': theme('colors.sand[700]'),
            '--tw-prose-invert-quotes': theme('colors.sand[100]'),
            '--tw-prose-invert-quote-borders': theme('colors.sand[700]'),
            '--tw-prose-invert-captions': theme('colors.sand[400]'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.sand[300]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.sand[600]'),
            '--tw-prose-invert-td-borders': theme('colors.sand[700]'),
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
